spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: smis
    password: root
    #url: jdbc:mysql://localhost:3306/smis?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:log4jdbc:mysql://49.234.79.216:3306/sims?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .ftl

  # springboot-mail配置
  mail:
    host: smtp.gmail.com
    username: tan13621251388@gmail.com
    password: 12345
    properties:
      smtp:
        auth: true;
        starttls: true;
        required: true;
      mail:
        smtp:
          ssl:
            enable: true;


logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
